studyportal/accounts/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView,PasswordResetCompleteView,PasswordResetConfirmView,PasswordResetView
app_name="accounts"
urlpatterns=[
    
   path('register',views.register,name="register"),
  path('admin_login',views.admin_login,name="admin_login"),
  path('user_login',views.user_login,name="user_login"),
 path('admin_editprofile',views.admin_editprofile, name="admin_editprofile"),
 path('user_editprofile',views.user_editprofile, name="user_editprofile"),
path('admin_profile',views.admin_profile, name="admin_profile"),
path('user_profile',views.user_profile, name="user_profile"), 
path('Logout',views.Logout, name="Logout"), 
path('forget_password/' , views.forget_Password , name="forget_password"),
path('change_password/<token>' , views.Change_Password , name="change_password"),
path('change_password_after_login' , views.change_password_after_login , name="change_password_after_login"),
  path('admin_change_password',views.admin_change_password,name="admin_change_password"),
]

studyportal/studyportal/urls.py
from re import template
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.urls.conf import include

admin.site.site_header = "Student Study Portal"
admin.site.site_title = "StudyPortal"
admin.site.index_title = "Students Details"
#from dashboard import views as dash_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('dashboard.urls')),
    path('accounts/',include('accounts.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view( template_name='users/password_reset.html', success_url=reverse_lazy('password_reset_done')),name='password_reset'),
   
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),      
]
 

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studyportal/accounts/models.py
from datetime import datetime
from django.db import models
from email.mime import image
from email.policy import default
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
# Create your models here.

class Register(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    branch= models.CharField(max_length=100)
    def __str__(self):
       return self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User,default="1", on_delete=models.CASCADE, related_name="profile")
   # user = models.OneToOneField(User,default="1", on_delete=models.CASCADE)   
    #forget_password_token = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images",default="default/user.png")
    date_joined = models.DateTimeField(default=now)
    last_login = models.DateTimeField(default=now)
    
    def __str__(self):
       return f'{self.user} profile'

   

studyportal/accounts/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from numpy import number
from accounts.models import *
from accounts.models import Profile 



class UserUpdateForm(forms.ModelForm):
    

    class Meta:
        model = User
        fields = [ 'first_name','last_name','email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

studyportal/accounts/views.py
from multiprocessing import context
from random import choices
import re
from django.shortcuts import redirect, render , HttpResponse
from . forms  import *
from django.contrib.auth import views 
from django.contrib import messages
from django.views import generic
from django.contrib.auth  import authenticate,  login, logout
from django.contrib.auth.decorators import login_required
import requests
from accounts.models import  Profile
from accounts.forms import ProfileUpdateForm ,UserUpdateForm
from django.core.mail import send_mail,BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes 
from accounts.helpers import send_forget_password_mail 
import uuid
import threading
class EmailThread(threading.Thread):
    def __init__(self,emails):
         self.emails = emails
         threading.Thread.__init__(self)
    def run(self):
         self.emails.send(fail_silently=False)


# Create your views here.

def admin_login(request):
    if request.method=="POST":
        try:
          username = request.POST['username']
          password = request.POST['password']
          user = authenticate(username=username, password=password)
          if user.is_staff:
            login(request, user)
            return redirect("/admin_home")
        except Exception as e:
            messages.error(request, "Invalid Credentials")
                 
    return render(request,"instructor/admin_login.html")


def admin_change_password(request):
    user = request.user
    if request.method == "POST":
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        if user.check_password('{}'.format(old_password)) == False:
              messages.success(request, 'please old password was entered incorrectly Please enter it again.')
        else:        
            if  confirm_password == new_password:
               user.set_password( new_password)
               user.save()
               messages.success(request, 'Your password have chanded successfully.')
               return redirect( '/accounts/admin_login')  
              
            else:
                messages.success(request, 'Password did not match.')
    return render(request, "instructor/admin_change_password.html")






def register(request):
    if request.method=="POST":   
        username = request.POST['username']
        email = request.POST['email']
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        branch = request.POST['branch']
        Value = {
               'username':username,
                'firstname':first_name,
                'lastname':last_name,
                'email':email,
                'branch':branch
            }
       
        regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]') 
        atSymbole = email.index('@')
        dot =email.rfind(".")
        error_mess=""
        if User.objects.filter(username=username).exists():
            error_mess ="This User name have been taken Please try other"
        if User.objects.filter(email=email).exists():
            error_mess ="This email id is already exist"
        if len(username) > 15:  
              error_mess = "username should be under 15 charecter" 
        if(regex.search(username) != None):
                 error_mess = "username must be in alphabets"
                  
        if(regex.search(first_name) != None):
            error_mess = "Name must be in alphabets"  
        if password != confirm_password:  
              error_mess = "Passwords do not match."     
        if  dot != -1:  
            if  (dot <= atSymbole + 3): 
                error_mess = " Please check Your typed email, 3 or 4 character  required before dot"    
            if  (dot != len(email)-4 and dot != len(email)-3):
                error_mess = " Please check Your typed email, After dot, 3 or 2 character required"
        else:
            error_mess = "Please check Your typed email, dot is required after  @"
        if not error_mess:
         user = User.objects.create_user(username, email, password)
         Register.objects.create(user=user,branch=branch)
         user.first_name = first_name
         user.last_name = last_name
         user.save()
         return render(request, 'user_login.html')  

        else:
            context={
                'error':error_mess,
                'values':Value
              } 
            return render(request,"users/register.html",context)       
    return render(request,"users/register.html")




def user_login(request):
    if request.method=="POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect("/user_home")
        else:
            messages.error(request, "Invalid Credentials")
                 
    return render(request,"user_login.html")

@login_required
def admin_profile(request):
    user = User.objects.get(id=request.user.id)  
    profile = Profile.objects.filter(user=user).get()  
    instance = profile
    return render(request, "instructor/admin_profile.html")


@login_required
def user_profile(request):

    return render(request, "users/user_profile.html")


@login_required
def user_editprofile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('/accounts/user_editprofile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/user_editprofile.html',context)




@login_required(login_url = 'login')
def admin_editprofile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('/accounts/admin_editprofile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, "instructor/admin_editprofile.html",context)
    
@login_required
def Logout(request):
    logout(request)
    messages.success(request, 'logout successfully.')
    return redirect('/')
#register and login complted===========================
def change_password_after_login(request):
   
    if request.method=='POST':
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        user = User.objects.get(username__exact = request.user.username)
        if user.check_password('{}'.format(old_password)) == False:
              messages.success(request, 'please old password was entered incorrectly Please enter it again.')
        else:        
            if  confirm_password == new_password:
               user.set_password( new_password)
               user.save()
               messages.success(request, 'Your password have chanded successfully.')
               return redirect( '/accounts/user_login')  
              
            else:
                messages.success(request, 'Password did not match.')

    return render(request,'users/change_password_after_login.html')




def Change_Password(request , token):
    context = {}
    try:
        profile_obj = Profile.objects.filter(forget_password_token = token).first()
        context = {'user_id' : profile_obj.user.id}
        
        if request.method == 'POST':
            new_password = request.POST.get('new_password')
            confirm_password = request.POST.get('reconfirm_password')
            user_id = request.POST.get('user_id')
            
            if user_id is  None:
                messages.success(request, 'No user id found.')
                return redirect(token)
                
            
            if  new_password != confirm_password:
                messages.success(request, 'password did not match.')
                return redirect(token)
                         
            
            user_obj = User.objects.get(id = user_id)
            user_obj.set_password(new_password)
            user_obj.save()
            messages.success(request, 'Your password have reset successfully.')
            return redirect('/accounts/user_login')
           
    except Exception as e:
        print(e)
    return render(request , 'change_password.html',context )



def forget_Password(request):
    try:
        if request.method == 'POST':
            email = request.POST.get('email')
            

studyportal/accounts/templates/users/change_password_after_login.html
{% extends "user/user_nav.html" %}
{% block title %} Log In {% endblock %}
{% block loginactive %} active {% endblock loginactive %}
{% load static %}
{% block body %}  


  <div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-6 offset-md-3">
            <div class="card my-3 shadow">
                <div class="card-body">
                      <h1 style="margin-bottom: 8%;">Change Password</h1>
                   
                    
                    <form method="POST" class="mt-4 mb-4">
                        {% csrf_token %}


            <div class="form-group">
            <input type="password" class="form-control" name="old_password" placeholder="Old Password" />
            </div>
            <div class="form-group">
          <input type="password" class="form-control" name="new_password" placeholder="New Password" /> 
         </div> 
         <div class="form-group">
        <input type="password" class="form-control" name="confirm_password" placeholder=" confirm New Password" />
        </div> 
      <div class="form-group">
                     <input type="submit" class="rlbtn" name="signup_submit"  value="Update Password" style="margin-left: -13%; width:150px;" />  
                     </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> 
  {% endblock body%} 

studyportal/accounts/templates/users/password_reset.html
{% extends 'base.html' %}
{% block title %}Password Reset Page{% endblock %}
{% load crispy_forms_tags %}
{% block body %}
 <div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-6 offset-md-3">
            <div class="card my-3 shadow">
                <div class="card-body">
                      <h1 >Forgot Password</h1>
                   
                    <div class="alert alert-info">
                   <center> Forgotten your password? Enter your registered email address below, and a mail will be sent with instructions to reset password</center>
                    </div>
                    <form method="POST" class="mt-4 mb-4">
                        {% csrf_token %}
                        {{ form|crispy }}
                     <input type="submit" class="rlbtn" name="signup_submit" value="Send Email" style="margin-left: -13%;" />  
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> 

  {% endblock body%}

studyportal/accounts/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Password Reset Complete{% endblock %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h1>Password Reset Complete</h1>
                   
                    <div class="alert alert-info">
                        <center>Your password reset is successful. Log in with new credentials</center>
                    </div>
                     <a href="{% url 'accounts:user_login' %}">Login</a>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

studyportal/accounts/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %} Reset Password {% endblock %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-6 offset-md-3">
            <div class="card my-3 shadow">
                <div class="card-body">
                      <h1 style="margin-bottom: 8%;">Reset Password</h1>
                   
                    
                    <form method="POST" class="mt-4 mb-4">
                        {% csrf_token %}
                        {{ form|crispy }}
                     <input type="submit" class="rlbtn" name="signup_submit" value="Reset Password" style="margin-left: -13%; width:150px;" />  
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> 

{% endblock body %}

studyportal/accounts/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Password Reset Done Page{% endblock %}
{% load crispy_forms_tags %}
{% block body%}
<div class="container">
    {% load static %}
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    
                  
                    <div class="alert alert-info">
                        <center ><p style="font-size:1.2rem;">An mail with instructions to reset password has been sent to the email you provided.</p>
                       <br><p> If you don’t receive an email, please make sure you’ve entered the address you registered with, and look for it in your spam folder. If you find it there, please mark it as “Safe” </p></center>

                    </div>
                  
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

studyportal/accounts/templates/users/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}
{% block registeractive %} active {% endblock registeractive %}
{% load static %}
{% block body %} 
<br>
 
<div id="login-box">
    <div class="items">
      <h1>User Register</h1>
        <form action="register" method="post"> {% csrf_token %}
         {%if error%}
        <div class="alert alert-danger "  role="alert" style="padding: 0;color: red;text-align: center;">
          <small class="manual-alter">{{error}}</small>
       </div>
       {%endif%}
      <input type="text" class="inputcss" name="username" placeholder="Username" value="{{values.username}}" required />
      <input type="email" class="inputcss" name="email" placeholder="E-mail" value="{{values.email}}" required/>
      <input type="text" class="inputcss" name="first_name" placeholder="First Name" value="{{values.firstname}}" required />
      <input type="text" class="inputcss"  name="last_name" placeholder="Last Name" value="{{values.lastname}}" required />
      <input type="password" class="inputcss" name="password" placeholder="Password"required />
      <input type="password" class="inputcss" name="confirm_password" placeholder="Confirm your password" required/>
       <select class=" inputcss" name="branch">
						  <option value="">Select Branch </option>
						  <option value="Computer Science">IT</option>
						  <option value="IT">Engineering</option>
						  <option value="Civil">Civil</option>
						  <option value="Electronics">Go</option>
						  <option value="Electric">Govt. Exam</option>
						    <option value="Electric">other</option>
				</select>
      <input type="submit"  class="rlbtn" name="signup_submit" value="Register" />
    </div>   
  </div>
 <br>
  {% endblock body %}

studyportal/accounts/templates/users/user_editprofile.html
{% extends "user/user_nav.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}

               <section>
      <div class="jumbotron jumbotron-fluid pb-1 bg-traperent">
        <div class="container-fluid">
            <h1 class="display-5 ">Edit Your profile information if You want</h1>
            
        </div>
      </div>
    </section>                 
     <div class="contentsection"> 
      <div class="media">
        <img class="rounded-circle " src="{{ user.profile.image.url }}" width="150px" height="150px">
        <div class="media-body">
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data" class="djform" action="user_editprofile">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend style="padding-top:8%;color:black;">Profile Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-primary" type="submit">Update</button>
          </div>
      </form>
    </div>
     
{% endblock body %}

studyportal/accounts/templates/users/user_profile.html
{% extends 'user/user_nav.html' %} 
{% block title %} Profile {% endblock %}
{% block profileactive %} active {% endblock profileactive %}

{% block css %}
{% endblock %}
{% block body %} 
<br>

<div class="container  login-box">
    <div class="row">
        <div class="col-lg-12 col-lg-offset-0">

            <div class="row pad">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        <div class="card-body">
                            <ul class="list-group">
                                <li class="list-group-item">
                                    <li class="list-group-item">
                                        
                                    Profile Picture:<strong class="float-right"> <img src="{{ user.profile.image.url }}" class="rounded-circle" alt="profile picture"
                                                width="150px" height="150px">
                                    </strong></li>
                                    
                                 <li class="list-group-item">
                                    Username: <strong class="float-right">{{user.username}}</strong>
                                </li> 
                                 <li class="list-group-item">
                                    Full Name: <strong class="float-right">{{request.user.get_full_name}}</strong>
                                </li> 
                                <li class="list-group-item">
                                    Email: <strong class="float-right">{{user.email}}</strong>
                                </li>
                                 <li class="list-group-item">
                                    <a href="{%url 'accounts:user_editprofile'%}"><button class="btn btn-primary">Update Profile</button></a> 
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock body %} 