studyportal/accounts/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView,PasswordResetCompleteView,PasswordResetConfirmView,PasswordResetView
app_name="accounts"
urlpatterns=[
    
   path('register',views.register,name="register"),
  path('admin_login',views.admin_login,name="admin_login"),
  path('user_login',views.user_login,name="user_login"),
 path('admin_editprofile',views.admin_editprofile, name="admin_editprofile"),
 path('user_editprofile',views.user_editprofile, name="user_editprofile"),
path('admin_profile',views.admin_profile, name="admin_profile"),
path('user_profile',views.user_profile, name="user_profile"), 
path('Logout',views.Logout, name="Logout"), 
path('forget_password/' , views.forget_Password , name="forget_password"),
path('change_password/<token>' , views.Change_Password , name="change_password"),
path('change_password_after_login' , views.change_password_after_login , name="change_password_after_login"),
  path('admin_change_password',views.admin_change_password,name="admin_change_password"),
]

studyportal/dashboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="dashboard"
urlpatterns=[
    path('',views.index,name="index"),
   path('user_home',views.user_home,name="user_home"),
   path('admin_home',views.admin_home,name="admin_home"), 
   path("forum", views.forum, name="forum"),
   path("discussion/<int:myid>", views.discussion, name="discussion"),
   path("showallusers", views.show_all_users, name="showallusers"),
   path('delete_user/<int:pk>',views.delete_user,name="delete_user"),
   path('delete_post/<int:pk>',views.delete_post,name="delete_post"),
    path('delete_reply/<int:pk>',views.delete_reply,name="delete_reply"),
 path('upload_notes', views.upload_notes, name='upload_notes'),
 path('view_mynotes', views.view_mynotes, name='view_mynotes'),
 path('delete_mynotes/<int:pk>/', views.delete_mynotes, name='delete_mynotes'),
 path('pending_notes', views.pending_notes, name='pending_notes'),
path('assign_status/<int:pk>', views.assign_status, name='assign_status'),
path('accepted_notes', views.accepted_notes, name='accepted_notes'),
path('rejected_notes', views.rejected_notes, name='rejected_notes'),
path('all_notes', views.all_notes, name='all_notes'),
 path('delete_notes/<int:pk>', views.delete_notes, name='delete_notes'),
path('delete-records/', views.delete_notes, name='delete_notes'),
path('view_allnotes', views.view_allnotes, name='view_allnotes'),
path('notessharing', views.notessharing, name='notessharing'),
path('edit_post/<int:pk>/', views.edit_post, name='edit_post'),
path('edit_reply/<int:pk>/', views.edit_reply, name='edit_reply'),

 ]

studyportal/studyportal/urls.py
from re import template
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.urls.conf import include

admin.site.site_header = "Student Study Portal"
admin.site.site_title = "StudyPortal"
admin.site.index_title = "Students Details"
#from dashboard import views as dash_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('dashboard.urls')),
    path('accounts/',include('accounts.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view( template_name='users/password_reset.html', success_url=reverse_lazy('password_reset_done')),name='password_reset'),
   
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),      
]
 

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studyportal/templates/instructor/admin_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Study Portal- Admin Dashboard</title>
    {% load static %}
    <!--boostrap cdn-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <!-- Boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!--my CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />

    <!--google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
    <!--DataTable-->
    <link rel="stylesheet" href="{% static 'js/plugins/datatables/dataTables.bootstrap4.min.css' %}"/>
   <link rel="stylesheet" id="css-main" href="{% static 'css1/codebase.min.css' %}"/>

</head>
  <body>
<div id="page-container" class="sidebar-o sidebar-inverse side-scroll page-header-fixed main-content-narrow">
<!--Strat Sidebar-->>
<nav id="sidebar">
        <div id="sidebar-scroll">
          <div class="sidebar-content">
            <div class="content-header content-header-fullrow px-15">
              <div class="content-header-section sidebar-mini-visible-b">
                  <span class="content-header-item font-w700 font-size-xl float-left animated fadeIn"> </span>
                  <span class="text-dual-primary-dark">c</span><span class="text-primary">b</span>
               </div>
               <div class="content-header-section text-center align-parent sidebar-mini-hidden">
                  <button type="button" class="btn btn-circle btn-dual-secondary d-lg-none align-v-r" data-toggle="layout" data-action="sidebar_close">
                  <i class="fa fa-times text-danger"></i></button>
                   <div class="content-header-item">
                      <a class="link-effect font-w700" href="">
                         <i class='bx bxs-book-reader text-primary'style="font-size:1.9rem; margin-left:-5%; "></i>
                        <span class="font-size-xl text-primary" style="margin-right:-1%;font-size: 1.8rem;font-weight: 700;font-family: 'Archivo Black', sans-serif;">Study Portal</span>
                      </a>
                    </div>
                </div>
            </div>
  <div class="content-side content-side-full content-side-user px-10 align-parent">
      <div class="sidebar-mini-visible-b align-v animated fadeIn">
          <img src="{% static 'imgage/admin.jpg' %}" alt="">
      </div>
      <div class="sidebar-mini-hidden-b text-center">
        <a class="img-link" href="be_pages_generic_profile.html">
          <img class="img-avatar" src="{% static 'images/admin.jpg' %}" alt="">
        </a>
        <ul class="list-inline mt-10">
          <li class="list-inline-item">
             <a class="link-effect text-dual-primary-dark font-size-xs font-w600 text-uppercase" href="{% url 'dashboard:admin_home' %}">{{ request.user.username }}</a>
          </li>
          <li class="list-inline-item">
              <a class="link-effect text-dual-primary-dark" href="{% url 'accounts:Logout' %}">
            <i class='bx bxs-left-arrow'></i>
             </a>
          </li>
        </ul>
      </div>
  </div>

  <div class="content-side content-side-full">
        <ul class="nav-main">
            <li class="open">
            <a href="{%url 'dashboard:admin_home'%}"><i class="fas fa-home"></i><span class="sidebar-mini-hide">Home</span></a>
            </li>
            <li>
            <a class="nav-submenu" data-toggle="nav-submenu"> <i class='bx bxs-notepad'></i><span class="sidebar-mini-hide"></span> Notes</a>
        <ul>
          <li>
            <a href="{%url 'dashboard:pending_notes'%}">Pending Notes</a>
          </li>
          <li>
            <a href="{%url 'dashboard:accepted_notes'%}">Accepted Notes</a>
          </li> 
          <li>
           <a href="{%url 'dashboard:rejected_notes'%}">Rejected Notes</a>
          </li>
         <li>
            <a href="{%url 'dashboard:all_notes'%}">All Notes</a>
         </li>
      </ul>
           </li>
            <li class="open">
                <a href="{%url 'dashboard:forum'%}"><i class="bx bxs-message-dots"></i><span class="sidebar-mini-hide">Disscussion Forum</span></a>
            </li>
            <li>
              <a  href="{%url 'dashboard:showallusers'%}"><i class="bx bxs-group"></i></i><span class="sidebar-mini-hide"> User</span></a>
            </li>
            <br><br>
            <li>
            <a class="nav-submenu" data-toggle="nav-submenu"><i class='bx bxs-cog'></i><span class="sidebar-mini-hide"></span>Settings</a>
      <ul>
          <li>
            <a href="{%url 'accounts:admin_change_password'%}">Change Password</a>
          </li>
          <li>
            <a href="{%url 'accounts:admin_profile'%}">Profile</a>
          </li>
      </ul>
          </li>
      </ul>
    
    </div>
 </div>
</div>
</nav>
<!--End Sidebar-->
{% include "instructor/admin_nav.html" %}
 {% if messages %} {% for msg in messages %}
      <div class="alert alert-{{msg.tags}} alert-dismissible fade show my-0">
        <strong>{{ msg }}</strong>
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      {% endfor %} {% endif %}
{% block body %}
{% endblock body %}

</div>

 <script>
      if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href)
      }
    </script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        
    <script>
        $(".remove-notes").click(function () {
            confirmation = confirm("Are you sure to delete");
            if (confirmation) {
                let elm = this;
                let id = elm.getAttribute("notesid").toString();
                console.log(id)
            
            
                $.ajaxSetup({
                headers: {
                    "X-CSRFToken": $("[name=csrfmiddlewaretoken]").val(),
                },
                });
                console.log(id);
                $.ajax({
                type: "POST",
                url: "{% url 'dashboard:delete_notes' %}",
            
                data: {
                    notesid: id,
                },
                success: function (resp) {
                    // console.log(status);
                    // resp means response
                    console.log("data is coming");
                    console.log(resp.msg);
                    elm.parentNode.parentNode.remove();
    
                    document.querySelector('.message').innerHTML = resp.msg;
                },
                error: function (resp) {
                    console.log(resp);
                },
                });
            }
            }); 
    </script>

 <!-- Codebase Core JS -->
         <script src="{% static 'js/core/jquery.min.js' %}"></script>
        <script src="{% static 'js/core/popper.min.js' %}"></script>
        <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/core/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'js/core/jquery.scrollLock.min.js' %}"></script>
        <script src="{% static 'js/core/jquery.appear.min.js' %}"></script>
        <script src="{% static 'js/core/jquery.countTo.min.js' %}"></script>
        <script src="{% static 'js/core/js.cookie.min.js' %}"></script>
        <script src="{% static 'js/codebase.js' %}"></script>

        <!-- Page JS Plugins -->
       <script src="{% static 'js/plugins/datatables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <!-- Page JS Code -->
        <script src="{% static 'js/pages/be_tables_datatables.js' %}"></script> 
    </body>
</html>

studyportal/templates/instructor/admin_home.html
{% extends 'instructor/admin_base.html' %}
{% load static %}
{% block body %} 

<style>
.container1 {
	background-color: lightgrey;
	border-radius: 8px;
}

h2, h4 {
	padding: 10px;
}

.mydiv:hover {
	transform: translateY(-10px)
}

.glow {
	font-size: 80px;
	color: #fff;
	text-align: center;
	-webkit-animation: glow 1s ease-in-out infinite alternate;
}

@-webkit-keyframes glow {
  from {
  text-shadow :0 0 10px #fff, 0 0 20px #fff, 0 0 30px #e60073,
	0 0 40px #e60073, 0 0 50px #e60073, 0 0 60px #e60073, 0 0 70px #e60073;
  }

  to {
	text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px
		#ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
  }
}
</style>

            <main id="main-container">
                <div class="content">
 
                    <div class="row gutters-tiny invisible shadow" data-toggle="appear">
                    
                        <!-- Row #1 -->
                         <div class="col-6 col-md-4 col-xl-3 box" >
                            <a class="block text-center" href="{% url 'dashboard:pending_notes' %}">
                                <div class="block-content ribbon ribbon-bookmark ribbon-crystal ribbon-left "style=" background-color: #e6e600; ;">
                                    <div class="ribbon-box" style="color:#000;font-size:1.5rem;">{{pending_notes}}</div>
                                    <p class="mt-5">
                                        <i class='bx bxs-book-add'style="font-size:3.1rem;color: #fff;"></i>
                                    </p>
                                    <p class="font-w600 " style=" color:#000;font-weight:700; font-size:1.3rem;">Pending Notes</p>
                                </div>
                            </a>
                        </div>
                        <div class="col-6 col-md-4 col-xl-3 box" >
                            <a class="block text-center" href="{% url 'dashboard:accepted_notes' %}">
                                <div class="block-content ribbon ribbon-bookmark ribbon-crystal ribbon-left "style=" background-color: green;">
                                    <div class="ribbon-box" style="color:#000;font-size:1.5rem;">{{accepted_notes}}</div>
                                    <p class="mt-5">
                                        <i class='bx bxs-book-add'style="font-size:3.1rem;color: #eee5e5;"></i>
                                    </p>
                                    <p class="font-w600 " style=" color:#000;font-weight:700; font-size:1.3rem;">Accepted Notes</p>
                                </div>
                            </a>
                        </div>
                        <div class="col-6 col-md-4 col-xl-3 box">
                            <a class="block text-center" href="{% url 'dashboard:rejected_notes' %}">
                                <div class="block-content ribbon ribbon-bookmark ribbon-crystal ribbon-left "style="background-color:red;">
                                    <div class="ribbon-box" style="color:#000;font-size:1.5rem;">{{rejected_notes}}</div>
                                    <p class="mt-5">
                                         <i class='bx bxs-book'style="font-size:3.1rem;color: #eee5e5;"></i>
                                    </p>
                                    <p class="font-w600" style=" color:#000;font-weight:700; font-size:1.3rem;">Rejected Notes</p>
                                </div>
                            </a>
                        </div>
                        <div class="col-6 col-md-4 col-xl-3 box">
                            <a class="block text-center" href="{% url 'dashboard:all_notes' %}">
                                <div class="block-content ribbon ribbon-bookmark ribbon-crystal ribbon-left "style="background-color:blue;">
                                    <div class="ribbon-box" style="color:#000;font-size:1.5rem; ">{{all_notes}}</div>
                                    <p class="mt-5">
                                        <i class='bx bxs-folder-open'style="font-size:3.1rem;color: #eee5e5;"></i>
                                    </p>
                                    <p class="font-w600 "style=" color:#000;font-weight:700; font-size:1.3rem;">All Notes</p>
                                </div>
                            </a> 
                        </div>

                        <!-- END Row #1 --> 
                    </div>
                    
                </div> 
                
       
<div class="container card  mt-4"  style="width:88%;">
	<div class="card-body">
      <h1 class="text-success text-center"></h1>
      <h4 class="text-center text-danger">Recently Logged In users</h4>	<br>
      <table id="datatable" class="table table-striped table-bordered"  id="datatable">
		     <thead style="background-color : #607d8b;color:white;">
					  <tr>
					    	<th scope="col">ID</th>
                <th scope="col">Profile</th>
               <th scope="col">Username</th>
               <th scope="col">Last Login</th>
              <th scope="col">Join date</th>
             <th scope="col">Action</th>
					  </tr>
				</thead>

				<tbody>
				{% for userData in data %}
          <tr>
             <th scope="row">{{userData.id}}</th>
             <td><img style="width: 40px; border-radius:15px;" src="{{userData.image.url}}" alt="this is it."></td>
             <td>{{userData.user.username}}</td>
             <td> {{userData.user.last_login }}</td>
            <td>{{ userData.user.date_joined }} </td>
         <td>

        <a href="{% url 'dashboard:delete_user' userData.id %}"> <button class="btn btn-danger btn-sm" onclick="window.mytest()">Delete</button></a>
        <script type="text/javascript">window.mytest = function() { var isValid = confirm('Are you sure to Delete this user?');
        if (!isValid) { event.preventDefault();  alert("It wont delete. Yay!");}}</script>
            
        </td>
       </tr>
    {% endfor %}
		</tbody>
	</table>
</div>
</div>

</main>


{% endblock body %}

studyportal/templates/instructor/assign_status.html
{% extends 'instructor/admin_base.html' %}
{% load static %}
{% block body %}
<style>
    .fontcss{
 font-family: 'Poppins', sans-serif;
font-weight:bold;}
</style>
<div id="page-container" class="sidebar-o sidebar-inverse side-scroll page-header-fixed main-content-narrow">
        <main id="main-container">
        <div class="container my-5">
         <h2 class="text-center fontcss mt-4 mb-4" >Assign Status</h2>
        <hr>

       <form method="post">
        {% csrf_token %}
        <label class="fontcss">Notes ID</label>
        <input type="text" name="noteid" class="form-control" value="{{notes.id}}" readonly>

        <label class="mt-4 fontcss">Status</label>
        <select name="status" class="form-control fontcss">
        <option value="Accept">Accept</option>
        <option value="Reject">Reject</option>
        </select>
        <br>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>

</div>
</main>
 </div>
{% endblock body %}

studyportal/templates/instructor/pending_notes.html
{% extends 'instructor/admin_base.html' %}
{% load static %}
{% block body %}
<style>
.tfont {
  font-size: 1rem;
  font-weight: 400;
font-family: 'Poppins', sans-serif;
 
}
.usertable{
           box-shadow: 4px 4px 4px 4px lightgray;
          width: 100%;
         background-color: #eee5e5;
         padding-top:1%;
		  overflow-x: visible;
       }
</style>
<div id="page-container" >
 <!-- Main Container -->
<main id="main-container">
<!-- Page Content -->
<h3 class="text-center notesText">Pending Notes</h3><br> 
<div class="content">   
	           
<div class=" container usertable  " ><div >

<table id="datatable" class=" mt-4 table table-bordered table-striped table-vcenter js-dataTable-full-pagination" style=" color:gray;" >
<thead style="background-color : #607d8b; color:white;" >
    <tr>
		 <th scope="col">S.No</th>
        <th scope="col">Uploaded By</th>
        <th scope="col">Uploading Date</th>
        <th scope="col">Branch</th>
        <th scope="col">Subject</th>
        <th scope="col">Download Notes</th>
		<th scope="col">File Type</th>
		<th scope="col">Description</th>
		<th scope="col">Status</th>
		<th scope="d-none d-sm-table-cell">Assign Status</th>
		<th scope="col">Action</th>
	</tr>
</thead>
<tbody>
				{% for i in pnotes %}
    <tr>
        <th class="tfont" scope="row">{{forloop.counter}}</th>
        <td class="tfont">{{i.user.username}}</td>
        <td class="tfont">{{i.uploadingdate}}</td>
        <td class="tfont">{{i.branch}}</td>
        <td class="tfont">{{i.subject}}</td>
		<td class="tfont"><a href="{{i.notesfile.url}}" class="btn btn-success btn1css" download style="background-color:green;">Download</a></td>
		<td class="tfont">{{i.filetype}}</td>
	    <td class="tfont">{{i.description}}</td>
        <td class="tfont">{{i.status}}</td>
		 <td class="tfont"><a href="{% url 'dashboard:assign_status' i.id %}" class="btn btn-success btn1css" style="background-color:green;">Assign&nbsp;Status</a></td>
        <td class="tfont">

        <a href="{% url 'dashboard:delete_notes' i.id %}"> <button class="btn btn-danger btn-sm" style="background-color:red;" onclick="window.mytest()">Delete</button></a>
        <script type="text/javascript">window.mytest = function() { var isValid = confirm('Are you sure to Delete this user?');
        if (!isValid) { event.preventDefault();  alert("It wont delete. Yay!");}}</script>
            
        </td>
        
    </tr>
    {% endfor %}
				</tbody>
</table>
</div>
</div>
</div>
 <!-- END Page Content -->
</main>
<!-- END Main Container -->
</div>
{% endblock body %}


 

studyportal/templates/instructor/sidebar.html
<link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
{% load static %}
<nav id="sidebar">
        <div id="sidebar-scroll">
          <div class="sidebar-content">
            <div class="content-header content-header-fullrow px-15">
              <div class="content-header-section sidebar-mini-visible-b">
                  <span class="content-header-item font-w700 font-size-xl float-left animated fadeIn"> </span>
                  <span class="text-dual-primary-dark">c</span><span class="text-primary">b</span>
               </div>
               <div class="content-header-section text-center align-parent sidebar-mini-hidden">
                  <button type="button" class="btn btn-circle btn-dual-secondary d-lg-none align-v-r" data-toggle="layout" data-action="sidebar_close">
                  <i class="fa fa-times text-danger"></i></button>
                   <div class="content-header-item">
                      <a class="link-effect font-w700" href="">
                         <i class='bx bxs-book-reader text-primary'style="font-size:1.9rem; margin-left:-5%; "></i>
                        <span class="font-size-xl text-primary" style="margin-right:-1%;
                     font-size: 1.8rem;
                  font-weight: 700;
                 font-family: 'Archivo Black', sans-serif;">Study Portal</span>
                      </a>
                    </div>
                </div>
            </div>
  <div class="content-side content-side-full content-side-user px-10 align-parent">
      <div class="sidebar-mini-visible-b align-v animated fadeIn">
          <img src="{% static 'imgage/admin.jpg' %}" alt="">
      </div>
      <div class="sidebar-mini-hidden-b text-center">
        <a class="img-link" href="be_pages_generic_profile.html">
          <img class="img-avatar" src="{% static 'images/admin.jpg' %}" alt="">
        </a>
        <ul class="list-inline mt-10">
          <li class="list-inline-item">
             <a class="link-effect text-dual-primary-dark font-size-xs font-w600 text-uppercase" href="{% url 'dashboard:admin_home' %}">{{ request.user.username }}</a>
          </li>
          <li class="list-inline-item">
              <a class="link-effect text-dual-primary-dark" href="{% url 'accounts:Logout' %}">
              <i class='bx bxs-left-arrow'></i>
             </a>
          </li>
        </ul>
      </div>
  </div>

  <div class="content-side content-side-full">
        <ul class="nav-main">
            <li class="open">
            <a href="{%url 'dashboard:admin_home'%}"><i class="fas fa-home"></i><span class="sidebar-mini-hide">Home</span></a>
            </li>
            <li>
            <a class="nav-submenu" data-toggle="nav-submenu"> <i class='bx bxs-notepad'></i><span class="sidebar-mini-hide"></span> Notes</a>
        <ul>
          <li>
            <a href="{%url 'dashboard:pending_notes'%}">Pending Notes</a>
          </li>
          <li>
            <a href="{%url 'dashboard:accepted_notes'%}">Accepted Notes</a>
          </li> 
          <li>
           <a href="{%url 'dashboard:rejected_notes'%}">Rejected Notes</a>
          </li>
         <li>
            <a href="{%url 'dashboard:all_notes'%}">All Notes</a>
         </li>
      </ul>
           </li>
            <li class="open">
                <a href="{%url 'dashboard:forum'%}"><i class="bx bxs-message-dots"></i><span class="sidebar-mini-hide">Disscussion Forum</span></a>
            </li>
            <li>
              <a  href="{%url 'dashboard:showallusers'%}"><i class="bx bxs-group"></i></i><span class="sidebar-mini-hide"> User</span></a>
            </li>
            <br><br>
            <li>
            <a class="nav-submenu" data-toggle="nav-submenu"><i class='bx bxs-cog'></i><span class="sidebar-mini-hide"></span>Settings</a>
      <ul>
          <li>
            <a href="{%url 'accounts:admin_change_password'%}">Change Password</a>
          </li>
          <li>
            <a href="{%url 'accounts:admin_profile'%}">Profile</a>
          </li>
      </ul>
          </li>
      </ul>
    
    </div>
 </div>
</div>
</nav>