studyportal/accounts/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView,PasswordResetCompleteView,PasswordResetConfirmView,PasswordResetView
app_name="accounts"
urlpatterns=[
    
   path('register',views.register,name="register"),
  path('admin_login',views.admin_login,name="admin_login"),
  path('user_login',views.user_login,name="user_login"),
 path('admin_editprofile',views.admin_editprofile, name="admin_editprofile"),
 path('user_editprofile',views.user_editprofile, name="user_editprofile"),
path('admin_profile',views.admin_profile, name="admin_profile"),
path('user_profile',views.user_profile, name="user_profile"), 
path('Logout',views.Logout, name="Logout"), 
path('forget_password/' , views.forget_Password , name="forget_password"),
path('change_password/<token>' , views.Change_Password , name="change_password"),
path('change_password_after_login' , views.change_password_after_login , name="change_password_after_login"),
  path('admin_change_password',views.admin_change_password,name="admin_change_password"),
]

studyportal/dashboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="dashboard"
urlpatterns=[
    path('',views.index,name="index"),
   path('user_home',views.user_home,name="user_home"),
   path('admin_home',views.admin_home,name="admin_home"), 
   path("forum", views.forum, name="forum"),
   path("discussion/<int:myid>", views.discussion, name="discussion"),
   path("showallusers", views.show_all_users, name="showallusers"),
   path('delete_user/<int:pk>',views.delete_user,name="delete_user"),
   path('delete_post/<int:pk>',views.delete_post,name="delete_post"),
    path('delete_reply/<int:pk>',views.delete_reply,name="delete_reply"),
 path('upload_notes', views.upload_notes, name='upload_notes'),
 path('view_mynotes', views.view_mynotes, name='view_mynotes'),
 path('delete_mynotes/<int:pk>/', views.delete_mynotes, name='delete_mynotes'),
 path('pending_notes', views.pending_notes, name='pending_notes'),
path('assign_status/<int:pk>', views.assign_status, name='assign_status'),
path('accepted_notes', views.accepted_notes, name='accepted_notes'),
path('rejected_notes', views.rejected_notes, name='rejected_notes'),
path('all_notes', views.all_notes, name='all_notes'),
 path('delete_notes/<int:pk>', views.delete_notes, name='delete_notes'),
path('delete-records/', views.delete_notes, name='delete_notes'),
path('view_allnotes', views.view_allnotes, name='view_allnotes'),
path('notessharing', views.notessharing, name='notessharing'),
path('edit_post/<int:pk>/', views.edit_post, name='edit_post'),
path('edit_reply/<int:pk>/', views.edit_reply, name='edit_reply'),

 ]

studyportal/studyportal/urls.py
from re import template
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.urls.conf import include

admin.site.site_header = "Student Study Portal"
admin.site.site_title = "StudyPortal"
admin.site.index_title = "Students Details"
#from dashboard import views as dash_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('dashboard.urls')),
    path('accounts/',include('accounts.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view( template_name='users/password_reset.html', success_url=reverse_lazy('password_reset_done')),name='password_reset'),
   
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),      
]
 

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studyportal/dashboard/models.py
from datetime import datetime
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
from email.mime import image
from email.policy import default
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from dashboard.validators import validate_file

# Create your models here.





   

class Post(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    post_id = models.AutoField
    post_content = models.TextField(max_length=5000,verbose_name="")
    timestamp= models.DateTimeField(default=now)
    branch=models.CharField(default='',max_length=200)
    image = models.ImageField(upload_to="images",default="")
    def __str__(self):
       return f'{self.user1} Post'

class Replie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    reply_id = models.AutoField
    reply_content = models.TextField(max_length=5000,verbose_name="")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default='')
    timestamp= models.DateTimeField(default=now)
    image = models.ImageField(upload_to="images",default="")
    def __str__(self):
       return f'{self.user1} Post'




import os
from django.core.exceptions import ValidationError


def validate_file_extension(value):
  ext = os.path.splitext(value.name)[1]   
  valid_extensions = ('.pdf', '.ppt', '.doc')  
  if not ext.lower() in valid_extensions:
    raise ValidationError('Unsupported file.')

class Upload_Notes(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    uploadingdate = models.CharField(max_length=30)
    branch = models.CharField(max_length=30)
    subject = models.CharField(max_length=50)
    notesfile = models.FileField(null=True,validators=(validate_file_extension, ))
    filetype = models.CharField(max_length=30)
    description = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=15)

    def __str__(self):
          return f'{self.user} notes'

studyportal/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Study Portal</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
      integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
      crossorigin="anonymous"
    />
     <!-- Boxicons -->
    <link href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"rel="stylesheet"/>
    <!--my Css-->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!--google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-white">
          <i class='bx bxs-book-reader'style="font-size:1.8rem; color:blue"></i>
        <a class="navbar-brand py-0 logost" href="/">Study Portal</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto hovereffect">
         <li class="nav-item">
              <a
                class="nav-link active dropcss py-0"
                aria-current="page"
                href="/"
              >
              Home
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link active dropcss py-0"
                aria-current="page"
                href="{%url 'accounts:register'%}"
              >
                Register
              </a>
            </li>
             
           

            <li class="nav-item dropdown " >
              <a class="nav-link dropdown-toggle py-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Login
              </a>
              <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{%url 'accounts:user_login'%}">User </a>
                <a class="dropdown-item" href="{%url 'accounts:admin_login'%}">Admin</a>
              
              </div>
            </li>
            {% comment %} <li class="nav-item">
              <a
                class="nav-link active dropcss py-0"
                aria-current="page"
                href="#about"
              >
                About
              </a>
            </li>
             {% endcomment %}

           
          </ul>
        </div>
      </nav>
    </header>

    <main>
      {% if messages %} {% for msg in messages %}
      <div class="alert alert-{{msg.tags}} alert-dismissible fade show my-0">
        <strong>{{ msg }}</strong>
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      {% endfor %} {% endif %} {% block body %}{% endblock body %}
    </main>
    <script>
      if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href)
      }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

studyportal/templates/discussion.html
{% load static %}
{% if user.is_superuser or user.is_staff %}
<html lang="en" class="no-focus">
    <head>
      <!--Bootstrap CDN-->>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
   <!--Boxicon-->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!--google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
    <!--My CSS-->
   <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
  <link rel="stylesheet" id="css-main" href="{% static 'css1/codebase.min.css' %}"/>

    </head>
    <body>
    <div id="page-container" class="sidebar-o sidebar-inverse side-scroll page-header-fixed main-content-narrow">
           
         {% include "instructor/sidebar.html" %}
         {% include "instructor/admin_nav.html" %}
            <!-- Main Container -->
          <main id="main-container">
              <!-- Page Content -->
             <div class="content">

 <style>
              .margin{
                margin-top:5%;
                 
              }
                  .post{
                   
                    font-weight:600;
                   font-family: 'Poppins', sans-serif;
                   
                  } 
            .text{
                    font-weight:400;
                   font-family: 'Poppins', sans-serif;
                 
                  } 
            .font{
                   font-weight:600;
                   }
            .forumcardheader {
                display: flex;
               align-items: center;
               border-bottom-width: 1px;
               padding-top: 0;
              padding-bottom: 0;
              padding-right: 0.625rem;
              height: 3.5rem;
              text-transform: uppercase;
              background-color: #fff;
              border-bottom: 1px solid rgba(26, 54, 126, 0.125);
             font-weight:600;
            }
         .f{
            font-weight:900;
           }
       .f2{
           font-weight:900;
          font-size:2.5rem;
         }
</style>   



{% else %}
  {% include "user/user_nav.html" %}
{% endif %}
{% load crispy_forms_tags %}
{% block body %}

<br><section>
      <div >
        <div class="container-fluid jumbotron"  style="margin-bottom: 5%;    text-align: center;">

            <center><h5 class="display-5 mb-4 f2 margin  ">Aad reply on this post </h5></center>
            <center><a href="{%url 'dashboard:forum'%}"><button class="btn btn-primary mb-4 text">Go to forum Home page</button></a> </center>

        </div>
      </div>
    </section>
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-header">
                    <div class="media flex-wrap w-100 align-items-center"> <img src="/media/{{post.image}}"
                            class="d-block ui-w-40 rounded-circle" alt="profileimage"style="width: 40px;height: 40px;">
                        <div class="media-body ml-3" style="text-transform: uppercase;"> <a data-abc="true">{{post.user1}}</a>
                        </div>
                        <div class="text-muted small ml-3">
                            <div class="post">Date and Time Of Post :</div>
                            <div><strong class="f">{{post.timestamp}}</strong></div>
                        </div>
                    </div>
                </div>         
                <div class="card-body">
                    <p class="text">{{post.post_content|linebreaks}}</p>
                </div>
                <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                    {% if user.is_superuser or user.is_staff %}
                        <a href="{% url "dashboard:edit_post" pk=post.id %}" data-abc="true"><button class="btn btn-light text" style="color:blue; font-size: 13px;">Edit</button>  </a>
                        {% endif %}
                    <div class="px-4 pt-3"> <button type="button" class="btn btn-primary text" data-target="#reply" data-toggle="modal"><i
                      class="ion ion-md-create"></i>&nbsp; Reply</button> </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% for reply in replies %}
    <div class="container-fluid mt-10">
      <div class="row">
          <div class="col-md-12">
              <div class="card mb-4 forumcardcss">
                  <div class="card-header forumcardheader">
                      <div class="media flex-wrap w-100 align-items-center imgcss"> <img src="/media/{{reply.image}}"  
                              class="d-block ui-w-40 rounded-circle" alt="profileimage"style="width: 40px;height: 40px;">  <p class="ml-4 usernamecss">  {{reply.user}} </p>
                           <div class="media-body ml-3"> <a href="/discussion/{{post.id}}" data-abc="true">  </a>
                          </div>
                          <div class="text-muted small">
                            
                            <div><strong class="f">{{reply.timestamp}}</strong></div>
                        </div>
                           {% if user.is_superuser or user.is_staff %}
                         
                            	&nbsp;	&nbsp; 	&nbsp;	&nbsp; <a href="{% url 'dashboard:delete_reply' reply.id %}"> <button class="btn btn-danger btn-sm text" onclick="window.mytest()">Delete</button></a>
       <script type="text/javascript">window.mytest = function() { var isValid = confirm('If you click ok then its delete this post and related reply on it. Are you sure to delete?');if (!isValid) { event.preventDefault();  alert("It wont delete. Yay!");}}</script>
                            
                            {% endif %}
                      </div>
                      
                  </div>         
                  <div class="card-body forumcardbody">
                      <p class="text">{{reply.reply_content|linebreaks}}</p>
                  </div>

                  <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">                  
                  {% if user.is_superuser or user.is_staff %}
                  <a href="{% url "dashboard:edit_reply" pk=reply.id %}" data-abc="true"><button class="btn btn-light text" style="color:blue; font-size: 13px;">Edit </button>  </a>
                 {% endif %}
                    {% if post.user1 == request.user %}
                  <a href="{% url "dashboard:edit_reply" pk=reply.id %}" data-abc="true"><button class="btn btn-light text" style="color:blue; font-size: 13px;">Edit </button>  </a>
                 {% endif %}
                  {% if reply.user == request.user %}
                  <a href="{% url "dashboard:edit_reply" pk=reply.id %}" data-abc="true"><button class="btn btn-light text" style="color:blue; font-size: 13px;">Edit </button>  </a>
                 {% endif %}
                  </div>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}


<div class="modal fade" id="reply" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% if user.is_authenticated %}
        <div class="modal-body">
          <form action="/discussion/{{post.id}}" method="POST"> {% csrf_token %}
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Post Your Solution Here</label>
              <input type="hidden" name="post_id" value="{{post.id}}">
              {{form|crispy}}
          </div>
          {% else %}
          <h3>Please Login first to post a reply</h3>
          {% endif %}
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Post Solution</button>
        </div>
      </div>
    </div>
  </div>

 
</div>
</main>
</div>   
</div>
 <!-- Codebase Core JS -->
<script src="{% static 'js/core/jquery.min.js' %}"></script>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/core/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/core/jquery.scrollLock.min.js' %}"></script>
<script src="{% static 'js/core/jquery.appear.min.js' %}"></script>
<script src="{% static 'js/core/jquery.countTo.min.js' %}"></script>
<script src="{% static 'js/core/js.cookie.min.js' %}"></script>
<script src="{% static 'js/codebase.js' %}"></script>

</body>
</html>
{% endblock body %}
 

studyportal/templates/edit_post.html
{% load static %}
{% if user.is_superuser or user.is_staff %}
<html lang="en" class="no-focus">
    <head>
      <!--Bootstrap CDN-->>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
   <!--Boxicon-->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!--google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
    <!--My CSS-->
   <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
   <link rel="stylesheet" id="css-main" href="{% static 'css1/codebase.min.css' %}"/>

    </head>
    <body>
    <div id="page-container" class="sidebar-o sidebar-inverse side-scroll page-header-fixed main-content-narrow">
           
         {% include "instructor/sidebar.html" %}
         {% include "instructor/admin_nav.html" %}
            <!-- Main Container -->
          <main id="main-container">
              <!-- Page Content -->
             <div class="content">

{% else %}
  {% include "user/user_nav.html" %}
{% endif %}
{% load static %}
{% block body %}
{% load crispy_forms_tags %}
<style>
    .f2{
           font-weight:800;
          font-size:2rem;
         }
</style>
<div class="container">

    <form method="POST">
        <div class="form-group">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 mt-4 f2" style="margin-top:10%;">Update Post</legend>
        </fieldset>
         <label style="font-size:1rem; font-weight:bold;">Post Content</label>
        {{form|crispy}}
        <div class="form-group">
            <button href="" class="btn btn-primary" type="Update">
            Update
            </button>
        </div>
    </div>
    </form>
</div>
</div>
</main>
</div>   
</div>
 <!-- Codebase Core JS -->
<script src="{% static 'js/core/jquery.min.js' %}"></script>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/core/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/core/jquery.scrollLock.min.js' %}"></script>
<script src="{% static 'js/core/jquery.appear.min.js' %}"></script>
<script src="{% static 'js/core/jquery.countTo.min.js' %}"></script>
<script src="{% static 'js/core/js.cookie.min.js' %}"></script>
<script src="{% static 'js/codebase.js' %}"></script>

</body>
</html>
{% endblock body%}

studyportal/templates/edit_reply.html
{% load static %}
{% if user.is_superuser or user.is_staff %}
<html lang="en" class="no-focus">
    <head>
      <!--Bootstrap CDN-->>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
   <!--Boxicon-->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <!--google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
    <!--My CSS-->
   <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
   <link rel="stylesheet" id="css-main" href="{% static 'css1/codebase.min.css' %}"/>

    </head>
    <body>
    <div id="page-container" class="sidebar-o sidebar-inverse side-scroll page-header-fixed main-content-narrow">
           
         {% include "instructor/sidebar.html" %}
         {% include "instructor/admin_nav.html" %}
            <!-- Main Container -->
          <main id="main-container">
              <!-- Page Content -->
             <div class="content">




{% else %}
  {% include "user/user_nav.html" %}
{% endif %}
{% load static %}
{% block body %}
{% load crispy_forms_tags %}
<style>
    .f2{
           font-weight:800;
          font-size:2rem;
         }
</style>
<div class="container ">

    <form method="POST">
        <div class="form-group">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 mt-4 f2" >Update Reply</legend>
        </fieldset>
         <label style="font-size:1rem; font-weight:bold;">Reply Content</label>
        {{form|crispy}}
        <input type="hidden" name="post_id" value="{{post_id}}"> 
        <div class="form-group">
            <button href="" class="btn btn-primary" type="Update">
            Update
            </button>
        </div>
    </div>
    </form>
</div>
</div>
</main>
</div>   
</div>
 <!-- Codebase Core JS -->
<script src="{% static 'js/core/jquery.min.js' %}"></script>
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/core/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/core/jquery.scrollLock.min.js' %}"></script>
<script src="{% static 'js/core/jquery.appear.min.js' %}"></script>
<script src="{% static 'js/core/jquery.countTo.min.js' %}"></script>
<script src="{% static 'js/core/js.cookie.min.js' %}"></script>
<script src="{% static 'js/codebase.js' %}"></script>

</body>
</html>
{% endblock body%}