studyportal/accounts/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView,PasswordResetCompleteView,PasswordResetConfirmView,PasswordResetView
app_name="accounts"
urlpatterns=[
    
   path('register',views.register,name="register"),
  path('admin_login',views.admin_login,name="admin_login"),
  path('user_login',views.user_login,name="user_login"),
 path('admin_editprofile',views.admin_editprofile, name="admin_editprofile"),
 path('user_editprofile',views.user_editprofile, name="user_editprofile"),
path('admin_profile',views.admin_profile, name="admin_profile"),
path('user_profile',views.user_profile, name="user_profile"), 
path('Logout',views.Logout, name="Logout"), 
path('forget_password/' , views.forget_Password , name="forget_password"),
path('change_password/<token>' , views.Change_Password , name="change_password"),
path('change_password_after_login' , views.change_password_after_login , name="change_password_after_login"),
  path('admin_change_password',views.admin_change_password,name="admin_change_password"),
]

studyportal/dashboard/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="dashboard"
urlpatterns=[
    path('',views.index,name="index"),
   path('user_home',views.user_home,name="user_home"),
   path('admin_home',views.admin_home,name="admin_home"), 
   path("forum", views.forum, name="forum"),
   path("discussion/<int:myid>", views.discussion, name="discussion"),
   path("showallusers", views.show_all_users, name="showallusers"),
   path('delete_user/<int:pk>',views.delete_user,name="delete_user"),
   path('delete_post/<int:pk>',views.delete_post,name="delete_post"),
    path('delete_reply/<int:pk>',views.delete_reply,name="delete_reply"),
 path('upload_notes', views.upload_notes, name='upload_notes'),
 path('view_mynotes', views.view_mynotes, name='view_mynotes'),
 path('delete_mynotes/<int:pk>/', views.delete_mynotes, name='delete_mynotes'),
 path('pending_notes', views.pending_notes, name='pending_notes'),
path('assign_status/<int:pk>', views.assign_status, name='assign_status'),
path('accepted_notes', views.accepted_notes, name='accepted_notes'),
path('rejected_notes', views.rejected_notes, name='rejected_notes'),
path('all_notes', views.all_notes, name='all_notes'),
 path('delete_notes/<int:pk>', views.delete_notes, name='delete_notes'),
path('delete-records/', views.delete_notes, name='delete_notes'),
path('view_allnotes', views.view_allnotes, name='view_allnotes'),
path('notessharing', views.notessharing, name='notessharing'),
path('edit_post/<int:pk>/', views.edit_post, name='edit_post'),
path('edit_reply/<int:pk>/', views.edit_reply, name='edit_reply'),

 ]

studyportal/studyportal/urls.py
from re import template
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.urls.conf import include

admin.site.site_header = "Student Study Portal"
admin.site.site_title = "StudyPortal"
admin.site.index_title = "Students Details"
#from dashboard import views as dash_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('dashboard.urls')),
    path('accounts/',include('accounts.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view( template_name='users/password_reset.html', success_url=reverse_lazy('password_reset_done')),name='password_reset'),
   
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),      
]
 

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studyportal/templates/user/notessharing.html
{% extends 'user/user_nav.html' %}
{% load static %}
{% block body %}
<style>
.inner_contanner {
  background-color:lightgray;
  border-radius: 8px;
  
}
.divcss{
  margin-top:12%;
}
h2,
h4 {
  padding: 10px;
   font-family: 'Poppins', sans-serif;
}
.divcss:hover{
  transform:translateY(-10px)
}
.bg{
     width: 100%;
    height:600px;
}
    
{% comment %} }class="bg "style="background-image: url('{% static "images/bgimg1.jpg"%}')"; {% endcomment %}
</style>
<section  class=" bg "style="background-color: rgb(233, 227, 227);";>
<div class="container">
  <div class="row">
   <div class="col-sm-4 text-center divcss">
   <div class="inner_contanner"style="background-color: rgb(73, 159, 240);;">
   <h2 style="color:rgb(29, 252, 22);"><i class='bx bxs-file-export'styel="background: var(--light-blue);"></i></h2>
   <a href="{%url 'dashboard:upload_notes'%}"><h4 class="text-body">Upload Notes</h4></a>
   </div>
   </div>
   <div class="col-sm-4 text-center divcss" >
   <div class="inner_contanner" style="background-color:yellow;">
   <h2 class="text-primary ">{{mynotes}}</h2>
   <a href="{%url 'dashboard:view_mynotes'%}"><h4 class="text-body">My Notes</h4></a>
   </div>
   </div>

   <div class="col-sm-4 text-center divcss" >
   <div class="inner_contanner"style="background-color:green;">
   <h2 class="text-primary ">{{allnotes}}</h2>
   <a href="{%url 'dashboard:view_allnotes'%}"><h4 class="text-body">All Notes</h4></a>
   </div>
   </div>  
</div>
</div>
</section>
{% endblock body %}

studyportal/templates/user/upload_notes.html
{% extends 'user/user_nav.html' %}
{% load static %}
{% block body %}

<div class="container card shadow mt-5"
		style="font-family: 'IBM Plex Sans', sans-serif;">
		<a href="{%url 'dashboard:notessharing'%}"><button class="btn btn-primary d-inline mt-2 " style="margine-left:-14px;">Go Back</button></a>
	<div class="card-body">
	<h2 class="text-center text-danger">Upload Notes</h2>
	<hr>
		<div class="row">
			<div class="col-sm-6">
				<img src="{% static 'images/study.jpg' %}" style="width: 90%; height: 500px" class="mt-3">
			</div>

			<div class="col-sm-6">
                <form method="post" enctype="multipart/form-data" class="mt-4">
                    {% csrf_token %}
  <div class="form-group mt-4">
  
    <input type="text" class="form-control" placeholder="Enter Subject" name="subject">

  </div>
  <div class="form-group mt-4">
    
    <select class="form-control" name="branch">
						  <option value="">Select Branch </option>
						  <option value="Computer Science">Computer Science</option>
						  <option value="IT">IT</option>
						  <option value="Civil">Civil</option>
						  <option value="Electronics">Electronics</option>
						  <option value="Electric">Electric</option>
						    <option value="Electric">other</option>
						</select>
                         </div>
                        <div class="form-group mt-4">
                       <select class="form-control" name="filetype">
						<option value="PDF"> Select File Type</option>
						<option value="PDF">PDF</option>
						<option value="PPT">PPT</option>
						<option value="DOC/DOCX">DOC/DOCX</option>
						<option value="TXT">TXT</option>
						<option value="ZIP/RAR">ZIP</option>
					  </select>
					   {%if error%}
        <div class="alert alert-danger "  role="alert" style="padding: 0;color: red;text-align: center;">
          <small class="manual-alter">{{error}}</small>
       </div>
       {%endif%}
                     </div>
  <div class="form-group mt-4">
    <input type="file" name="notesfile" name="notesfile" class="form-control" style="padding:0;">

  </div>
  <div class="form-group mt-4">
    <textarea class="form-control" name="description" rows="3"placeholder="Write some description here about notes!"></textarea>
  </div>
  <div class="form-group mt-4">
   <center> <input type="submit" class="btn btn-primary mt-2 d-inline" value="Submit"> </center>

  </div>
</form>
</div>
</div>
</div>
  
</div>
{% endblock body%}

studyportal/templates/user/user_home.html
{% extends 'user/user_nav.html' %}
{% load static %}
{% block body %}

 <section style="background-color:#fff;">
  <marquee class="marquee" behavior="scroll" direction=left" "> </marquee>
<section class="container text-center">
  <h2>Welcome</h2>
  <hr class="hr"> <br>  
<div class="container">
  <div class="row my-4">
    <div class="col">

        <div class="container-fluid">
          <div class="row">
            <div class="col-sm d-flex">
              <a href="{%url 'dashboard:forum'%}">
              <div class="card card-body flex-fill custumcss">
                 <img class="card-img-top" src="{% static 'images/forum.jpg' %}" alt="Notes image">
                <div class="card-body">
            <h5 class="card-title ">
             disscussion Forum
            </h5>
        <p class="hcardP">Have any  doubts or  questions, No problem post your question here and get solution from your friends!</p>
          </div>
              </div>
            </div>

             <div class="col-sm d-flex" >
              <a href="{%url 'dashboard:notessharing'%}">
              <div class="card card-body flex-fill custumcss">
                <img class="card-img-top" src="{% static 'images/notessharing.jfif' %}" alt="trans image">
                <div class="card-body">
            <h5 class="card-title ">
              Notes sharing
            </h5>
             <p class="hcardP">share you notes and E book here and find notes and E books uploaded by  others </p>
          </div>
              </div>
            </div>

          


            
          </div>
        </div>
      </div>
        
    </div>

       <br>       
         

    
           
  </section>
</section>
{% endblock body %}

studyportal/templates/user/user_nav.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Student-dashboard</title>
    <!--bootstrap CDN-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />


    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
      integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
      crossorigin="anonymous"
    />
    <!--Boxicon CDN-->
      <link href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"rel="stylesheet"/>
    <!--google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
   
     <!--Datatables bootstrap-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">


<!--MY CSS-->
 <link rel="stylesheet" href="{% static 'css/main.css' %}" />
     <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
     
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-white">
         <i class='bx bxs-book-reader'style="font-size:1.8rem; color:blue"></i>
        <a class="navbar-brand py-0 logost" href="/" >Study Portal</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto hovereffect">
           <li class="nav-item">
              <a
                class="nav-link active dropcss py-0"
                aria-current="page"
                href="{%url 'dashboard:user_home'%}"
              >
                Home
              </a>
            </li>
           
           
           
            
            

            <li class="nav-item dropdown dropcss">
              <a
                class="nav-link dropdown-toggle py-0"
                href="#"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Options
              </a>
              <div
                class="dropdown-menu dropdown-menu-right dpcss text-center"
                aria-labelledby="navbarDropdown"
              >
                <a class="dropdown-item" href="{% url 'dashboard:forum' %}">disscussion</a>
                

                <a class="dropdown-item" href="{% url 'dashboard:notessharing'  %}">Upload Notes</a>
              </div>
            </li>

           <li class="nav-item dropdown " >
              <a class="nav-link dropdown-toggle py-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <img src="{{ user.profile.image.url }}" class="rounded-circle" alt="profile picture"
                width="40px" height="40px">
              </a>
              <div class="dropdown-menu dropdown-menu-right  text-center" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{%url 'accounts:user_profile'%}">Profile</a>
                 <a class="dropdown-item" href="{%url 'accounts:change_password_after_login'%}">change Password</a>
                <a class="dropdown-item" href="{%url 'accounts:Logout'%}">Logout</a>

              </div>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <main>
      {% if messages %} {% for msg in messages %}
      <div class="alert alert-{{msg.tags}} alert-dismissible fade show my-0">
        <strong>{{ msg }}</strong>
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      {% endfor %} {% endif %} {% block body %}{% endblock body %}
    </main>
    <script>
      if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href)
      }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
  <!--Datatables bootstrap-->
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>

<script>
$(document).ready(function() {
    $('#datatable').DataTable();
} );
</script> 
</html>

studyportal/templates/user/view_allnotes.html
{% extends 'user/user_nav.html' %}
{% load static %}
{% block body %}

<br><br><br>
<a href="{%url 'dashboard:notessharing'%}" style="float: right;  margin-right: 114px;"><button class="btn btn-primary">Go Back</button></a>

<div class="container card shadow mt-5">

	<div class="card-body">
           <h4 class="text-center text-danger">View All Notes</h4>
			<br>
			<table id="datatable" class="table table-striped table-bordered" style="width:100%" id="datatable">
				<thead style="background-color : #607d8b;">
					<tr>
						<th>S.No</th>
						<th>Uploaded By</th>
						<th>Uploading Date</th>
						<th>Branch</th>
						<th>Subject</th>
						<th>Download Notes</th>
						<th>File Type</th>
						<th>Description</th>
						<th>Status</th>
					</tr>
					</thead>
				{% for i in notes %}
				<tbody>
				<tr>
                    <td>{{forloop.counter}}</td>
					<td>{{i.user.username}}</td>
					<td>{{i.uploadingdate}}</td>
					<td>{{i.branch}}</td>
					<td>{{i.subject}}</td>
					<td><a href="{{i.notesfile.url}}" class="btn btn-success" download>Download</a></td>
					<td>{{i.filetype}}</td>
					<td>{{i.description}}</td>
					<td>{{i.status}}</td>

                </tr>
				{% endfor %}
				</tbody>
			</table>
    </div>
</div>

{% endblock body %}

studyportal/templates/user/view_mynotes.html
{% extends 'user/user_nav.html' %}
{% load static %}
{% block body %}
<br><br><br>

	<a href="{%url 'dashboard:notessharing'%}" style="float: right;    margin-right:114px;"><button class="btn btn-primary">Go Back</button></a>
<div class="container card shadow mt-5">
	<div class="card-body">
  <h1 class="text-success text-center"></h1>
            <h4 class="text-center text-danger">View My Notes</h4>
			<br>

			<table id="datatable" class="table table-striped table-bordered" style="width:100%" id="datatable">
				<thead style="background-color : #607d8b;">
					<tr>
						<th>S.No</th>
						<th>Uploading Date</th>
						<th>Branch</th>
						<th>Subject</th>
						<th>Download Notes</th>
						<th>File Type</th>
						<th>Description</th>
						<th>Status</th>
						<th>Action</th>
					</tr>
				</thead>
				{% for i in notes %}
				<tbody>
				<tr>
                  <td>{{forloop.counter}}</td>
					<td>{{i.uploadingdate}}</td>
					<td>{{i.branch}}</td>
					<td>{{i.subject}}</td>
					<td><a href="{{i.notesfile.url}}" class="btn btn-success" download>Download</a></td>
					<td>{{i.filetype}}</td>
					<td>{{i.description}}</td>
					<td>{{i.status}}</td>
				
					<td><a href="{% url 'dashboard:delete_mynotes' i.id %}" class="btn btn-danger" onclick="return confirm('Are your sure to Delete ?')">Delete</a></td>
					
                </tr>
				{% endfor %}
				</tbody>
	</table>
</div>
</div>
 {% endblock body %}